### ISSUE TITLE
Telegram output module

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Kassy#112]
Any plans for [Telegram Bot API](https://core.telegram.org/bots/api) support with [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api)?

**Comment by mrkno** [comment]
Not at present (a lot of work going on with hubot compatibility and slack stabilization), although it looks like it would be trivial to implement. If you want to give it a go there is some info on what needs to be done here: https://github.com/mrkno/Kassy/blob/master/doc/IntegrationCreation.md

**Comment by lagleki** [comment]
Some inspiration can be taken from Telegram-IRC gateway https://github.com/FruitieX/teleirc/issues

**Comment by phillipadsmith** [comment]
Howdy @mrkno @lagleki --

Many thanks for the feedback. :-)

I'm updating this issue to avoid duplicate work because I've hacked on this today and got the basics of a Telegram output integration working based on the Hipchat work.

I'll push to get a bit more than `sendMessage` implemented today and then drop a link here to a fork that you can take a peek at before sending a PR.

<img width="648" alt="telegram_and_1__node_main_js_--debug_telegram__node_" src="https://cloud.githubusercontent.com/assets/34128/14771844/d2b5bf30-0a4a-11e6-8359-11d6dec431e6.png">

**Comment by mrkno** [comment]
@phillipadsmith looking good so far!

**Comment by phillipadsmith** [comment]
@mrkno Couple of quick questions while I have your attention. :-) 

+ Is there a good module to test with that responds with an image? I'm looking to test `sendImage`.

+ Is there a better way to disable modules than moving them out of the modules folder?

I think that's it for now.

**Comment by mrkno** [comment]
- Respond with image: I would suggest 8ball because it does not require an API key.
- Individual modules? No. This is fairly high up our TODO list right now but not yet implemented. You can `kpm install/uninstall` for non pre-installed modules though or `/disable` to disable them all.

**Comment by phillipadsmith** [comment]
> Respond with image: I would suggest 8ball because it does not require an API key.

Working nicely, thanks! :-)

<img width="1155" alt="telegram_and_skype" src="https://cloud.githubusercontent.com/assets/34128/14774813/e068b1f4-0a6e-11e6-802b-1ea2d642c9ff.png">

**Comment by mrkno** [comment]
Looks good. Feel free to make a PR for this if you would like to include it in the project.

**Comment by phillipadsmith** [comment]
> Feel free to make a PR for this if you would like to include it in the project.

Yes, of course! That's the whole point. :-)

**Comment by Awarua-** [comment]
Looks like this has been completed, nice work.

**Comment by phillipadsmith** [comment]
👍
