### ISSUE TITLE
exports.match(...) breaks all modules when receiving images from Facebook

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Kassy#143]
If the chat receives anything besides text, `exports.match(text, commandPrefix)` assigns `text` to `undefined`
That leads to this error if the expressions of form `text.startsWith(...)` are present in the method

```
ERR! Error in getUserInfo TypeError: Cannot read property 'startsWith' of undefined
ERR! Error in getUserInfo     at Platform.exports.match (help.js:65:7)
ERR! Error in getUserInfo     at Platform.messageRxd (platform.js:52:39)
ERR! Error in getUserInfo     at facebook.js:133:7
```

Earlier I noticed this issue when testing the `disable` module and considered it was local but it persists. I've patched it in `disable.js` and now it's breaking `help.js`

**Comment by mrkno** [comment]
Just receiving images? I suggest checking that you have `v1.1.0` of `facebook-chat-api`.

Also have you pulled in master? The matcher api changed slightly for core modules recently.

**Comment by ParasDPain** [comment]
I am using `v1.1.0` of the `facebook-chat-api` and did a quick base merge on the testing machine, the issue was still present (there was an error in the `matcher` function) I'll detail more on it once I get home. 

But the issue was present last I checked. Can anyone try to replicate it?

**Comment by mrkno** [comment]
Try on the latest master now. I think https://github.com/concierge/Kassy/commit/4d41ebc1bc6caa3e7be5bc0e635322ec8a7b7159 will fix it.

**Comment by ParasDPain** [comment]
Yea that fixes it :+1: Should the shim stringify all values by default to avoid similar errors in the future?

**Comment by mrkno** [comment]
Probably should stringify `sender_name` and `body` given those are the only two which are required to be strings.
