### ISSUE TITLE
Process exits on update command.

### ISSUE THREAD

**Issue by Awarua-** [concierge/Kassy#147]
After the update command has finished performing npm update the process will likely exit.
This has been found to be independent of node version, and core integration.

Sometimes the problem would not occur when running with test without the debug command.

**Comment by mrkno** [comment]
Progress?

**Comment by Awarua-** [comment]
A stupid question, will get a stupid answer :expressionless:

**Comment by mrkno** [comment]
![mn](http://gifrific.com/wp-content/uploads/2013/04/Shocked-Troy-Walks-Into-Fire-With-Pizza-Community.gif)

**Comment by mrkno** [comment]
![sd](https://az616578.vo.msecnd.net/files/2015/03/09/635614651775814945-1624270294_tumblr_n9oe1n0iFb1tql584o1_500.gif)
