### ISSUE TITLE
docker-kassy

### ISSUE THREAD

**Issue by MatthewHartstonge** [concierge/Kassy#150]
Thinking about portability and ease of deployment, would you be keen for a docker image of kassy?
Could make it easier for testing/trialing kassy cases as well.

**Comment by mrkno** [comment]
Absolutely. We currently have it running on AWS so a docker deploy would be cool

**Comment by MatthewHartstonge** [comment]
@mrkno sweet, I'll have it wrapped tonight methinks. Would it be alright to sub-directory the project (it's easier/cleaner from a Docker point of view. If not, meh, I'll make it work.

In this case the proposed directory structure would end up looking like:

- README.md
- LICENSE.md
- .ci-files.yml
- .pullapprove.yml
- docs/
- kassy/
  - core/
  - modules/
  - main.js
  - .babelrc
  - package.json

**Comment by mrkno** [comment]
I'll have to ask @Awarua- about that one. My main concern is that if we pushed that change to the repository, the auto-updater would break all existing installations.

**Comment by MatthewHartstonge** [comment]
All good, for now I'll work around it :whale:
