### ISSUE TITLE
Associate module overrides hooked words from other modules

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Kassy#159]
If a word is associated to a phrase, the `associate` module overrides the message first before it reaches the appropriate module. 
A practical example is
 
`/associate personA rudeWord`

afterwards one can't 
`/slap personA` 

anymore. It becomes a race biased alphabetically.

**Comment by mrkno** [comment]
In some ways this is by design, in others it isn't. Given I'm planning to remove some other limitations, I may remove this one too at some point.

**Comment by mrkno** [comment]
resolved by https://github.com/concierge/Kassy/commit/f79aeba24426d9f2d911a5c346f2f89c52fc4de9
