### ISSUE TITLE
Create twitter listener to forward tweets to other networks

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Kassy#173]
I want to create a listener module/core_module/integration (whichever will be the best solution) to be always listening for tweets from specific people or tags and forward them to a specific facebook group chat or all group chats

Any pointers? Ideas?

**Comment by mrkno** [comment]
Curently that isnt very easy to do given how disconnected a module and an integration are. The simplest solution to the problem (until someone works out how to make it easier without rewriting a bunch of things) is to have a module which accepts some kind of `register` command.

When the register command is received it saves a handle to the `api` and `thread` objects, allowing you to forward as you desire.

**Comment by ParasDPain** [comment]
Is it possible to instruct the module to forward the thread data to the desired integration without manually prompting it through that integration?

Alternatively, running two bots at once using a shared storage could solve the issue.

**Comment by mrkno** [comment]
Currently no. Which is the reason for suggesting a `registration` like command above.

I want to deal with this problem cause it is useful functionality and is one of the reasons we don't currently have a way to loopback. Part of the problem is that it would require modification of each existing integration to fix (which already needs to be done for other reasons such as `getUsers`) which is time consuming.

**Comment by ParasDPain** [comment]
I see then it'd be faster to just open twitter than manually prompting the bot for it. 

Does this functionality goes in **4.0 milestone** or do we have different plans for that?

**Comment by mrkno** [comment]
4.0 would be a conservative estimate. There are a bunch of other things which are slowly being worked on in [feature/general-feature-enhancements](https://github.com/concierge/Kassy/tree/feature/general-feature-enhancements) for this milestone.

**Comment by mrkno** [comment]
Technically resolved by the **unstable** APIs `api.sendMessageToMultiple` and `exports.platform.getApis()` from https://github.com/concierge/Kassy/commit/573909343333724779a08d9b2b687411d45f03fb

**Comment by ParasDPain** [comment]
Awesome thanks!
