### ISSUE TITLE
Add platform property to event

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Kassy#181]
@mrkno I'm integrating more full-featured logging into the bot/module I'm working on, and I'd like to be able to store the platform that the message came from. 

Is this currently accessible anywhere? I don't see it in the event object, etc.

Many thanks in advance,

Phillip.

**Comment by mrkno** [comment]
The PR https://github.com/concierge/Kassy/pull/175 deals with this. It provides a string telling you where an event came from and methods for retrieving it again later.
